Repository PIVX-Labs/pivx-shield, pull requests merged in 2023-03, with the labels that each got.

#15 Add Testnet checkpoints
  src/checkpoint.rs
  src/transaction.rs
Labels: enhancement

#14 Fetch sapling params
  Cargo.toml
  js/pivx_shielding.js
  src/transaction.rs
  src/transaction/test.rs
Labels: enhancement

#18 Added typescript types
  js/package-lock.json
  js/package.json
  js/pivx_shielding.d.ts
  js/pivx_shielding.js
Labels: documentation, enhancement

#19 Various wasm fixes
  Cargo.toml
  src/checkpoint.rs
  src/transaction.rs
Labels: bug

#42 Fix max balance
  src/transaction.rs
Labels: bug

#43 Add single thread tx progress alternative
  src/transaction.rs
Labels: enhancement

#46 Updated readme and Cargo.toml
  Cargo.toml
  README.md
  build_multicore.sh
Labels: documentation
