Repository PIVX-Labs/pivx-shield, pull requests merged in 2023-11, with the labels that each got.

#60 Add view only support
  js/pivx_shield.js
  src/checkpoint.rs
  src/keys.rs
  src/transaction.rs
Labels: enhancement

#62 Add txid to createTransaction return obj
  README.md
  js/pivx_shield.js
Labels: enhancement

#61 Make ShieldData self contained
  js/pivx_shield.js
Labels: enhancement

#65 Fix private variables
  js/pivx_shield.js
Labels: bug

#69 Use array for diversifierIndex
  js/pivx_shield.js
Labels: bug

#70 Improve gh actions
  .github/workflows/rust.yml
  Makefile
  js/package-lock.json
Labels: enhancement

#67 Rewrite the js part to ts
  .gitignore
  Makefile
  js/package-lock.json
  js/package.json
  js/pivx_shield.js
  js/pivx_shield.ts
  js/tsconfig.json
Labels: documentation, enhancement
